project:
  type: website
  output-dir: docs

website:
  title: "Sebastian Sukstorf"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: projects.qmd
        text: Projekte
      - href: presentation.qmd
        text: Vortr√§ge
      - href: publication.qmd
        text: Publikationen
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastian-sukstorf/
      
  page-footer: 
    left: "Copyright 2025, Sebastian Sukstorf"

  reader-mode: false
  bread-crumbs: true
  search: true
  open-graph: true

  # Google Analytics (GA4)
  google-analytics: "G-E5JTBN5NH8"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
