project:
  type: website
  output-dir: docs

website:
  title: "Sebastian Sukstorf"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: entscheidungsbegleitung.qmd
        text: Entscheidungsbegleitung
      - href: workshops.qmd
        text: Workshops
      - href: projects.qmd
        text: Projekte
      - href: presentation.qmd
        text: Vorträge
      - href: publication.qmd
        text: Publikationen
      - href: about.qmd
        text: Über mich
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastian-sukstorf/

  page-footer:
    left: "© 2025 Sebastian Sukstorf"
    right: "Kontakt: info(at)sebastian.sukstorf.de"

  reader-mode: false
  bread-crumbs: true
  search: true
  open-graph: true

  google-analytics: "G-E5JTBN5NH8"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
